### ISSUE TITLE
Search in documentation ends up in 404

### ISSUE THREAD

**Issue by bosix** [confetti-framework/confetti#107]
## Steps to reproduce
* open https://www.confetti-framework.com/docs/get-started/meet.html
* input `database` into the search field; the suggestions appear
* hit enter
* see the error:
![image](https://user-images.githubusercontent.com/26360670/107258075-ae035200-6a3b-11eb-820d-1a6bcf61f644.png)

Neither my browser console nor my network traffic throw any errors.

**Comment by reindert-vetter** [comment]
Thanks @bosix

I have sent algolia a message. They are not very fast, but I hope they can fix it soon. The solution is not difficult.

**Comment by reindert-vetter** [comment]
@bosix They have already approved my pull request. It will take up to 24 hours for everything to be re-indexed.

Thanks again for reporting!

**Comment by reindert-vetter** [comment]
The problem is not solved yet. I sent them an email. Hopefully, it will be resolved soon.

**Comment by reindert-vetter** [comment]
It took a while, but it's fixed.
