### ISSUE TITLE
Wrong import?

### ISSUE THREAD

**Issue by marcelloh** [confetti-framework/confetti#114]
I see this in the main.go
```
import (
	"confetti-framework/bootstrap"
	"confetti-framework/config"
	"github.com/confetti-framework/contract/inter"
	"github.com/confetti-framework/foundation/http"
```
but I think, the first 2 lines should be a full url
```
	"github.com/confetti-framework/bootstrap"
	"github.com/confetti-framework/config"
```

**Comment by BrentChesny** [comment]
Looks correct to me. They're meant to pull in the bootstrap and config packages in your project. You should probably change the module name in `go.mod`.

**Comment by reindert-vetter** [comment]
@BrentChesny You are absolutely right. But maybe we should change it to `src`. Or do you have another idea?

**Comment by BrentChesny** [comment]
`src` could indeed be a good default module name. It makes clear that these are local packages. Users can then still change the module name as they wish for their project (i.e. to their github url).

**Comment by marcelloh** [comment]
I was just looking at what bootstrap did. And it's nothing to manipulate (I think), but maybe I'm wrong.
(I was trying to make a normal framework out of it, but there's a bit to much weird stuff in it to cope with)
