### ISSUE TITLE
init() in app.go

### ISSUE THREAD

**Issue by marcelloh** [confetti-framework/confetti#116]
Since I get shivers from init() functions (because it's a magic function), I was looking at this.

I think the line:
	bootContainer = decorator.Bootstrap(foundation.NewContainer())
can move inside the NewAppFromBoot()

I've tried it and see no difference.

**Comment by reindert-vetter** [comment]
You're right. In https://github.com/confetti-framework/confetti/discussions/105 I will put this in its own command (in foundation).
