### ISSUE TITLE
Move `app:serve` to `confetti-framework/foundation`

### ISSUE THREAD

**Issue by octoper** [confetti-framework/confetti#130]
It will be nice if  the `app:serve` command can be moved to the [confetti-framework/foundation](https://github.com/confetti-framework/foundation).

I know that this will require changes to the [confetti-framework/commands](https://github.com/confetti-framework/commands) template so the command does not appear in command line based applications and only appear in the web based applications.

**Comment by reindert-vetter** [comment]
I've looked at this before, but now I managed to put it down nicely. Processed in v0.23.1 and is backwards compatible.
https://github.com/confetti-framework/confetti/releases/tag/V0.23.1
https://github.com/confetti-framework/confetti/commit/98c755bf4aebdd62666a2c82dcbf0efcc90468b6
