### ISSUE TITLE
config/embed.go:4:2: package embed is not in GOROOT (/usr/local/go/src/embed)

### ISSUE THREAD

**Issue by noyce** [confetti-framework/confetti#131]
I'm new to golang and docker.I setup docker successfully but face this when i run docker-compose up in my confetti project
![image](https://user-images.githubusercontent.com/10207863/116906461-eba00180-ac5d-11eb-8768-54f345327f85.png)

**Comment by reindert-vetter** [comment]
It seems that it does not use Go version 1.16. I'll be looking at this today.

**Comment by reindert-vetter** [comment]
It is solved by the following:
https://github.com/confetti-framework/confetti/commit/e984bd652f6b4a805dfa37af99d564f50c4ac593

I will process this with other tweaks and test everything today and tomorrow. But you can make the above adjustment in your Dockerfile yourself.

**Comment by noyce** [comment]
Okay , thanks a lot!

**Comment by reindert-vetter** [comment]
@noyce Can you confirm that this was the solution?

**Comment by noyce** [comment]
![image](https://user-images.githubusercontent.com/10207863/117148386-cd5c1200-add3-11eb-87a0-3379e983279c.png)
The build is successful but i cannot ping the server, it fails to establish connection. At the same time I'm able to access the Mail hog endpoint.

**Comment by reindert-vetter** [comment]
@noyce My apologies, I couldn't reproduce at first. I have implemented the solution. See release [v0.23.2](https://github.com/confetti-framework/confetti/releases/tag/v0.23.2) You need to adjust the following: https://github.com/confetti-framework/confetti/compare/v0.23.1...v0.23.2

Can you indicate whether it works for you now?

**Comment by noyce** [comment]
![image](https://user-images.githubusercontent.com/10207863/117348029-5c962200-aec7-11eb-8220-9b4213822fc0.png)
I get this now,
err: exit status 1: stderr: go: github.com/confetti-framework/contract@v0.3.0: module lookup disabled by GOPROXY=off
: packages.Load error

**Comment by reindert-vetter** [comment]
@noyce I think there is still an old package from / contract. You can do the following:
`go get github.com/confetti-framework/contract@v0.3.0`

Or to update and install all packages:
`go get -u all`

Maybe I should document that. Goland (editor) does that automatically.

**Comment by noyce** [comment]
Yes it works for me now! thanks a lot. Yes i think this can be documented, it'll be helpful for laravel/php folks to get things started .

**Comment by reindert-vetter** [comment]
Done:
https://www.confetti-framework.com/docs/get-started/installation.html#update-modules
