### ISSUE TITLE
Installation standard version

### ISSUE THREAD

**Issue by marcelloh** [confetti-framework/confetti#98]
A normal way to use an external package, would be via a go get command, like:
go get github.com/confetti-framework/confetti
It has the advantage for having it only once on your computer (if you don't use a vendor setup).
What is the reason not to follow this?

When I do use that, I get some notifications:
github.com/confetti-framework/confetti imports
        lanvard/foundation/http: package lanvard/foundation/http is not in GOROOT (/usr/local/go/src/lanvard/foundation/http)
github.com/confetti-framework/confetti imports
        lanvard/http: package lanvard/http is not in GOROOT (/usr/local/go/src/lanvard/http)
github.com/confetti-framework/confetti imports
        lanvard/interface/http: package lanvard/interface/http is not in GOROOT (/usr/local/go/src/lanvard/interface/http)
github.com/confetti-framework/confetti imports
        lanvard/src/bootstrap: package lanvard/src/bootstrap is not in GOROOT (/usr/local/go/src/lanvard/src/bootstrap)

**Comment by reindert-vetter** [comment]
Thanks for your feedback! github.com/confetti-framework/Confetti is not an external package. It's like a template and mainly contains configuration. You are supposed to download that code and save it in your own git. If you download it with get, how can you, for example, adjust your routes? I will have to explain it more clearly in the documentation.

**Comment by marcelloh** [comment]
Look how other frameworks are doing this. (It's not that hard, and what you do now it quite uncommon.)
