### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by NWBY** [confetti-framework/confetti#99]
Big Laravel fan here and have just discovered Confetti and really liking it so far.

I’m wondering if there are any plans to implement a CLI tool similar to Artisan to generate new Models, Migrations, etc. 

Happy to discuss, plans and contribute to this if needed.

**Comment by Wulfheart** [comment]
I'm sure that there are plans for that.
However, I'd like to know if there is a concept of service providers in packages like laravel has. This would simplify the embedding of commands.
